// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCM_pGg-_TCcxD4Lt5FC794sKcjFrjgkU',
    appId: '1:909600456266:web:ca67cbc7ee4c0ec6bdf0b3',
    messagingSenderId: '909600456266',
    projectId: 'foood-82d9b',
    authDomain: 'foood-82d9b.firebaseapp.com',
    storageBucket: 'foood-82d9b.appspot.com',
    measurementId: 'G-E83SLLWJ5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5NX_eC1cWlWSlgLa-gEh9ULmWooFDYI',
    appId: '1:909600456266:android:7180053d23725ae8bdf0b3',
    messagingSenderId: '909600456266',
    projectId: 'foood-82d9b',
    storageBucket: 'foood-82d9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJu6Ge6HCFIqhzEKAVIkfpnyGjjHOfdg',
    appId: '1:909600456266:ios:f5016363345c446dbdf0b3',
    messagingSenderId: '909600456266',
    projectId: 'foood-82d9b',
    storageBucket: 'foood-82d9b.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
